const htmlPdf = require('html-pdf-node');

/**
 * Generates a PDF buffer from cover letter text.
 * @param {string} coverLetterText
 * @param {object} metadata  - { date, tone, generatedAt }
 * @returns {Promise<Buffer>}
 */
async function generateCoverLetterPDF(coverLetterText, metadata = {}) {
  const date = metadata.date || new Date().toLocaleDateString('en-US', {
    year: 'numeric', month: 'long', day: 'numeric',
  });

  const html = `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="UTF-8">
      <title>Cover Letter</title>
      <style>
        body {
          font-family: 'Times New Roman', serif;
          font-size: 12pt;
          line-height: 1.7;
          color: #333;
          max-width: 8.5in;
          margin: 0 auto;
          padding: 1in;
          background: white;
        }
        .header {
          text-align: center;
          margin-bottom: 28px;
          border-bottom: 2px solid #2c3e50;
          padding-bottom: 14px;
        }
        .header h1 { margin: 0; font-size: 18pt; font-weight: bold; color: #2c3e50; }
        .date { text-align: right; margin-bottom: 24px; font-size: 11pt; color: #555; }
        .content { white-space: pre-line; text-align: justify; }
        .footer {
          margin-top: 40px;
          text-align: center;
          font-size: 9pt;
          color: #aaa;
          border-top: 1px solid #ddd;
          padding-top: 12px;
        }
      </style>
    </head>
    <body>
      <div class="header"><h1>Cover Letter</h1></div>
      <div class="date">${date}</div>
      <div class="content">${coverLetterText.replace(/\n/g, '<br/>')}</div>
      <div class="footer">Generated by Resume Intelligence Suite · ${new Date().toLocaleString()}</div>
    </body>
    </html>
  `;

  const options = {
    format:          'A4',
    margin:          { top: '0.75in', right: '0.75in', bottom: '0.75in', left: '0.75in' },
    printBackground: true,
  };

  const pdfBuffer = await htmlPdf.generatePdf({ content: html }, options);
  return pdfBuffer;
}

/**
 * Builds a safe filename for the PDF download.
 * @param {object} metadata
 * @returns {string}
 */
function generatePDFFilename(metadata = {}) {
  const date     = new Date().toISOString().split('T')[0];
  const company  = metadata.company  ? `_${metadata.company.replace(/[^a-zA-Z0-9]/g,  '')}` : '';
  const position = metadata.position ? `_${metadata.position.replace(/[^a-zA-Z0-9]/g, '')}` : '';
  return `CoverLetter${company}${position}_${date}.pdf`;
}

module.exports = { generateCoverLetterPDF, generatePDFFilename };


// const htmlPdf = require('html-pdf-node');

// /**
//  * Generates a PDF from cover letter text
//  * @param {string} coverLetterText - The cover letter content
//  * @param {object} metadata - Additional metadata (name, date, etc.)
//  * @returns {Promise<Buffer>} PDF buffer
//  */
// async function generateCoverLetterPDF(coverLetterText, metadata = {}) {
//   try {
//     console.log('🔄 Generating PDF for cover letter...');

//     // Create HTML template for the cover letter
//     const html = `
//       <!DOCTYPE html>
//       <html>
//       <head>
//         <meta charset="UTF-8">
//         <title>Cover Letter</title>
//         <style>
//           body {
//             font-family: 'Times New Roman', serif;
//             font-size: 12pt;
//             line-height: 1.6;
//             color: #333;
//             max-width: 8.5in;
//             margin: 0 auto;
//             padding: 1in;
//             background: white;
//           }
          
//           .header {
//             text-align: center;
//             margin-bottom: 30px;
//             border-bottom: 2px solid #333;
//             padding-bottom: 15px;
//           }
          
//           .header h1 {
//             margin: 0;
//             font-size: 18pt;
//             font-weight: bold;
//             color: #2c3e50;
//           }
          
//           .date {
//             text-align: right;
//             margin-bottom: 20px;
//             font-size: 11pt;
//             color: #666;
//           }
          
//           .content {
//             white-space: pre-line;
//             text-align: justify;
//             margin-bottom: 30px;
//           }
          
//           .content p {
//             margin-bottom: 15px;
//           }
          
//           .footer {
//             margin-top: 40px;
//             text-align: center;
//             font-size: 10pt;
//             color: #888;
//             border-top: 1px solid #ddd;
//             padding-top: 15px;
//           }
          
//           @media print {
//             body {
//               margin: 0;
//               padding: 1in;
//             }
//           }
//         </style>
//       </head>
//       <body>
//         <div class="header">
//           <h1>Cover Letter</h1>
//         </div>
        
//         <div class="date">
//           ${metadata.date || new Date().toLocaleDateString('en-US', { 
//             year: 'numeric', 
//             month: 'long', 
//             day: 'numeric' 
//           })}
//         </div>
        
//         <div class="content">
//           ${coverLetterText.replace(/\n/g, '<br/>')}
//         </div>
        
//         <div class="footer">
//           Generated by AI Resume Analyzer - ${new Date().toLocaleString()}
//         </div>
//       </body>
//       </html>
//     `;

//     // PDF generation options
//     const options = {
//       format: 'A4',
//       margin: {
//         top: '0.75in',
//         right: '0.75in',
//         bottom: '0.75in',
//         left: '0.75in'
//       },
//       printBackground: true,
//       preferCSSPageSize: true
//     };

//     // Generate PDF buffer
//     const pdfBuffer = await htmlPdf.generatePdf({ content: html }, options);
    
//     console.log('✅ PDF generated successfully');
//     return pdfBuffer;

//   } catch (error) {
//     console.error('❌ Error generating PDF:', error);
//     throw new Error('Failed to generate PDF: ' + error.message);
//   }
// }

// /**
//  * Generates filename for the cover letter PDF
//  * @param {object} metadata - Metadata including company name, position, etc.
//  * @returns {string} Formatted filename
//  */
// function generatePDFFilename(metadata = {}) {
//   const date = new Date().toISOString().split('T')[0]; // YYYY-MM-DD format
//   const company = metadata.company ? `_${metadata.company.replace(/[^a-zA-Z0-9]/g, '')}` : '';
//   const position = metadata.position ? `_${metadata.position.replace(/[^a-zA-Z0-9]/g, '')}` : '';
  
//   return `CoverLetter${company}${position}_${date}.pdf`;
// }

// module.exports = {
//   generateCoverLetterPDF,
//   generatePDFFilename
// };